[package]
name = "sky-install"
version = "0.1.0"
authors = ["Jed Irvine <jedirv@gmail.com>"]


[dependencies]
zip = "0.3.0"
curl = "0.4.8"

[target."macos".dependencies]
git2 = "0.6.11"

[target."linux".dependencies]
git2 = "0.6.11"
